docker-4 ДЗ-17 "Docker: сети, docker-compose"
Otus-DevOps-2017-11/vchernovolov_microservices pull request #4
Opened 2018-02-18 15:14 UTC by vchernovolov

ДЗ-17 "Docker: сети, docker-compose"

2018-03-01 17:26 UTC, serjs requested changes

2018-03-01 17:26 UTC, serjs commented on reddit-microservices/.gitignore
> +docker-compose.yml
Привет! В коде ДЗ нам была допущена ошибка, нужно убрать compose из .gitignore и добавить его в гит

2018-03-01 18:49 UTC, vchernovolov commented on reddit-microservices/.gitignore
> +docker-compose.yml
привет!
убрал из .gitignore
добавил в репозиторий

2018-03-04 14:17 UTC, serjs approved these changes

2018-03-10 16:14 UTC, merged